### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by HIT-Ygq** [SlamCabbage/Optimized-SC-F-LOAM#3]
Hi,
terminate called after throwing an instance of 'pcl::IOException'
  what():  : [pcl::PCDWriter::writeBinary] Error during open!
你遇到过这样的问题嘛

**Comment by SlamCabbage** [comment]
> Hi,
> terminate called after throwing an instance of 'pcl::IOException'
> what(): : [pcl::PCDWriter::writeBinary] Error during open!
> 你遇到过这样的问题嘛

应该是保存pcd点云的文件夹没有提前创建吧

**Comment by pvela2017** [comment]
I'm facing the same problem, I changed the save directory path on the laserLoopOptimizationNode.cpp file but I still have the problem.

**Comment by pvela2017** [comment]
My bad, i forgot to compile again :s
