### ISSUE TITLE
some issues about laser Loop Optimization

### ISSUE THREAD

**Issue by Abl4-auto** [SlamCabbage/Optimized-SC-F-LOAM#6]
1、检测到闭环以后，为什么代码中使用闭环帧和闭环帧的地图匹配，而不是采用当前帧和闭环帧地图匹配，代码如下：
//    loopFindNearKeyframesCloud_edge(cureKeyframeCloud_edge, 0, _curr_kf_idx);
    loopFindNearKeyframesCloud_edge(cureKeyframeCloud_edge, 0, _loop_kf_idx);
    loopFindNearKeyframesCloud_edge(laserCloudCornerMap, submap_size, _loop_kf_idx);
//    loopFindNearKeyframesCloud_surf(cureKeyframeCloud_surf, 0, _curr_kf_idx);
    loopFindNearKeyframesCloud_surf(cureKeyframeCloud_surf, 0, _loop_kf_idx);
    loopFindNearKeyframesCloud_surf(laserCloudSurfMap, submap_size, _loop_kf_idx);
2、当前帧和闭环帧在map下匹配的结果，理论上应该是当前帧的位姿变化量，为什么代码中理解的是当前帧和闭环帧之间的位姿变换量？

**Comment by SlamCabbage** [comment]
你好
1. 对于对一个问题，是scan context的遗留问题（在它的github中已经修改）你可以按照这样来写：
loopFindNearKeyframesCloud_edge(cureKeyframeCloud_edge, 0, _curr_kf_idx);
// loopFindNearKeyframesCloud_edge(cureKeyframeCloud_edge, 0, _loop_kf_idx);
loopFindNearKeyframesCloud_edge(laserCloudCornerMap, submap_size, _loop_kf_idx);
loopFindNearKeyframesCloud_surf(cureKeyframeCloud_surf, 0, _curr_kf_idx);
// loopFindNearKeyframesCloud_surf(cureKeyframeCloud_surf, 0, _loop_kf_idx);
loopFindNearKeyframesCloud_surf(laserCloudSurfMap, submap_size, _loop_kf_idx);

2. 对于第二个问题，我没理解你的意思。但是我试着从回环约束部分讲一下：
当前帧和回环帧它们在odometry轨迹上有一个位姿变化关系 T_{curr}^{loop}
通过我们的scan2map得到它们的匹配位姿 \hat{T}_{curr}^{loop}
如果没有累积误差的存在，那么有如下关系：
T_{curr}^{loop} * { \hat{T}_{curr}^{loop}}^-1 = identity matrix
但是由于累积误差的存在，因此我们把这个误差作为图优化过程中的误差项之一：
e_i = T_{curr}^{loop} * { \hat{T}_{curr}^{loop}}^-1 

我们使用了gtsam的框架，这个框架只需要你给出你的loop constraint即\hat{T}_{curr}^{loop}，做为一个回环边，它能帮你自动地求解整个图优化问题

**Comment by Abl4-auto** [comment]
您好，第一个问题我已经明白了。然后可能第二个问题我没表述清楚，具体是代码中将当前帧点云和闭环帧点云分别利用里程计位姿转换到map坐标系下以后，每次ceres优化会对map坐标系下当前帧点云左乘一个优化矩阵变量，直至误差最小，所以最终优化出的变量理论上应该是当前帧里程计位姿的变化量，为什么代码认为的是当前帧和闭环帧之间的位姿变换量？

**Comment by SlamCabbage** [comment]
`每次ceres优化会对map坐标系下当前帧点云左乘一个优化矩阵变量`
我发现你在这一部分理解错误了，ceres求解过程不会改变输入的点云，我们在处理的时候都是copy一个点用上一次优化量位姿来改变copy点的坐标。
最终求出的odom就是刚刚讲到的\hat{T}_{curr}^{loop}。
你所说的当前帧的位姿变化量应该是P_{current}与Map_{current-1}计算得到的位姿变换，这里是P_{current}与Map_{loop-1}这个过程应该是慢于odometry。

**Comment by Abl4-auto** [comment]
您好，我确实对优化出的位姿具体指的是什么比较模糊。因为如果两帧点云都是在各自雷达坐标系下，那么ceres优化以后的结果肯定是相互间的位姿变化量。但是现在当前帧和闭环帧都变换到了统一的map坐标系，按照我的理解ceres求解过程确实不会改变输入的点云，不过copy的点刚开始是map坐标系下当前点，用上一次优化量位姿改变copy点的坐标以后，这个点是在什么坐标系下和map坐标系下闭环帧点云进行比对呢？

**Comment by SlamCabbage** [comment]
`上一次优化量位姿改变copy点的坐标以后，这个点是在什么坐标系下和map坐标系下闭环帧点云进行比对呢`
ceres的求解过程是一个迭代的过程，每一步是一个x+delta_x的更新过程，最终迭代完成求得到的x就是最开始map系下的P{current}与Map_{loop}的位姿变换即刚刚讲到的\hat{T}{curr}^{loop}。

**Comment by Abl4-auto** [comment]
您好，按照这么理解，ceres输入的当前点是Tcurrent_to_map * Pcurrent，闭环点是Tloop_to_map * Ploop：
 *nearKeyframes += *local2global(keyframeLaserClouds_edge[keyNear], keyframePosesUpdated[keyNear]);
然后最终迭代优化出的变量Tx会使得copy的点，达到近似这种关系Tx * Tcurrent_to_map*Pcurrent=Tloop_to_map * Ploop：
Tcurrent_to_loop=(Tloop_to_map)_逆 * Tx * Tcurrent_to_map，这么理解哪里出错了呢？

**Comment by SlamCabbage** [comment]
你好，我认真的思考了一下你所提的问题。你的理解是正确的，但是计算上面有一些问题，我帮你纠正一下。
我们假设odometry坐标系为map系，那么我们现在有当前帧和回环帧在世界坐标系下的位姿：
$T_{current}^{map}$， $T_{loop}^{map}$ 。
接下来就是对回环约束 $T_{current}^{loop}$ 的求解过程，这个过程有两种方式：
1. 在map系下的求解：
$T_x P_{curr}^{map} = P_{loop}^{map}$
那么可以更新世界坐标系当前帧的位姿
$\hat T_{current}^{map} = T_x T_{current}^{map}$
然后我们可以得到回环约束
$T_{current}^{loop} =(T_{loop}^{map})^{-1} \hat{T}_{current}^{map}$

2.在loop系的求解：
将 $P_{curr}$ 直接投影位姿 $T_{loop}^{map}$ 下，再进行点云优化求解
$T_x T_{loop}^{map} P_{curr} = P_{loop}^{map}$
这里求得的 $T_x$ 就是 $T_{loop}^{curr}$ ，对它取逆运算就得到了 $T_{current}^{loop}$ 回环约束

这两种方法其实本质是相同的，只是点云用于计算的坐标系不同。
代码也存在问题：
// loopFindNearKeyframesCloud_edge(cureKeyframeCloud_edge, 0, _curr_kf_idx);
loopFindNearKeyframesCloud_edge(cureKeyframeCloud_edge, 0, _loop_kf_idx);
loopFindNearKeyframesCloud_edge(laserCloudCornerMap, submap_size, _loop_kf_idx);
// loopFindNearKeyframesCloud_surf(cureKeyframeCloud_surf, 0, _curr_kf_idx);
loopFindNearKeyframesCloud_surf(cureKeyframeCloud_surf, 0, _loop_kf_idx);
loopFindNearKeyframesCloud_surf(laserCloudSurfMap, submap_size, _loop_kf_idx);
根据代码中的意思是第二种求解形式，因此在查找当前帧时，应该按照loopFindNearKeyframesCloud_edge(cureKeyframeCloud_edge, 0, _loop_kf_idx);这样的形式进行，但是loopFindNearKeyframesCloud_edge函数内需要将对应的点云改编成current pointcloud。


最后，非常感谢你能指出我代码中的问题！

**Comment by SlamCabbage** [comment]
如果你愿意尝试将代码修正并pull，我会非常感谢的！

**Comment by Abl4-auto** [comment]
您好，第一种方式确实没有问题，但是第二种方式如果按照您的理解那Tcurrent_loop * Tmap_loop * Pcurrent = Pmap_loop这个等式不成立啊， 是不是应该写成这样Tmap_loop * Tx * Pcurent = Pmap_loop，Tx才可以表示Tloop_current，但是这么写感觉又无法解释第二种求解代码

**Comment by SlamCabbage** [comment]
你好，这个式子是成立的。
举个航迹推导的例子，map系下T_k到T_{k+1}他们的位姿变换通过在T_k下的k+1帧点云与T_k下的k帧点云匹配得到T_k^{k+1}，然后得到T_{k+1}= T_k T_k^{k+1}。
那么可以理解成map系下T_{loop}到T_{curr}，T_{loop}下的curr点云与T_{loop}下的loop点云匹配到T_{loop}^{curr}，然后有T_x = T_{loop}^{curr}。可以得到 T_{loop} = T_{loop} T_x。

**Comment by Abl4-auto** [comment]
您好，我感觉您的解释还是存在一点问题，map系下T_k到T_(k+1) 他们的位姿变换应该通过T(k+1)下的k+1帧点云与Tk下的k帧点云匹配得到即Tx *  P(k+1) = Pk， 匹配出的Tx=Tk_(k+1)，而您说的T_k下的k+1帧点云与T_k下的k帧点云匹配对应的公式T_x * { Tk_(k+1) *  P(k+1) } = Pk，但是匹配出的Tx不等于Tk_(k+1)

**Comment by SlamCabbage** [comment]
你好，这个式子是成立的。
你可能需要再思考一下lidar odometry的过程，具体一点比如说第0帧和第1帧的匹配，我想你应该能理解了。
