### ISSUE TITLE
源码问题

### ISSUE THREAD

**Issue by CoderChen552** [SlamCabbage/Optimized-SC-F-LOAM#7]
同学，您好！我是想来请教一些问题，就是关于NDD-点云描述子这篇论文，因为当时看到您和原作者有交流，想问一下，您有没有遇到这这样的问题，就是运行了作者的源码，发现生成的二维描述子（经过makeNDD函数），存在-nan(ind)这样的非数据类型，这导致后面无法比较描述子之间的相似度。还是说需要一些额外处理。

**Comment by SlamCabbage** [comment]
NDD源码没太大问题，我的测试都是用的matlab版本。
打个广告，我最近做了一个新的描述子NDTMC，开源地址：https://github.com/SlamCabbage/NDTMC

**Comment by CoderChen552** [comment]
感谢回复 一定拜读 谢谢
